import { Component, signal, WritableSignal } from '@angular/core';
import { DevExChartComponent } from "./dev-ex-chart/dev-ex-chart.component";
import { PlotlyComponent } from "./plotly/plotly.component";
import { ChartjsComponent } from "./chartjs/chartjs.component";

@Component({
    selector: 'app-chart',
    standalone: true,
    imports: [
        DevExChartComponent,
        PlotlyComponent,
        ChartjsComponent
    ],
    templateUrl: './chart.component.html',
    styleUrl: './chart.component.css'
})
export class ChartComponent {
    fruitProduction: WritableSignal<FruitProduction[]> = signal(this.getFruitProductionData());

    getFruitProductionData(): FruitProduction[] {
        let fruitProductionData: FruitProduction[] = [
            { 'fruitName': "Apple", 'year': 2001, 'produced': 84 },
            { 'fruitName': "Apple", 'year': 2002, 'produced': 53 },
            { 'fruitName': "Apple", 'year': 2003, 'produced': 82 },
            { 'fruitName': "Apple", 'year': 2004, 'produced': 90 },
            { 'fruitName': "Orange", 'year': 2005, 'produced': 72 },
            { 'fruitName': "Orange", 'year': 2006, 'produced': 70 },
            { 'fruitName': "Orange", 'year': 2008, 'produced': 76 },
            { 'fruitName': "Orange", 'year': 2013, 'produced': 90 },
            { 'fruitName': "Orange", 'year': 2011, 'produced': 56 },
            { 'fruitName': "Mango", 'year': 2014, 'produced': 120 },
            { 'fruitName': 'Apple', 'year': 2015, 'produced': 136 },
            { 'fruitName': 'Banana', 'year': 2016, 'produced': 148 },
            { 'fruitName': 'Date', 'year': 2017, 'produced': 110 },
            { 'fruitName': 'Date', 'year': 2018, 'produced': 85 },
            { 'fruitName': 'Apple', 'year': 2019, 'produced': 139 },
            { 'fruitName': 'Banana', 'year': 2020, 'produced': 94 },
            { 'fruitName': 'Apple', 'year': 2021, 'produced': 100 },
            { 'fruitName': 'Orange', 'year': 2022, 'produced': 141 },
            { 'fruitName': 'Orange', 'year': 2023, 'produced': 94 },
            { 'fruitName': 'Apple', 'year': 2024, 'produced': 74 },
            { 'fruitName': 'Orange', 'year': 2025, 'produced': 116 },
            { 'fruitName': 'Banana', 'year': 2026, 'produced': 93 },
            { 'fruitName': 'Orange', 'year': 2027, 'produced': 93 },
            { 'fruitName': 'Date', 'year': 2028, 'produced': 62 },
            { 'fruitName': 'Orange', 'year': 2029, 'produced': 106 },
            { 'fruitName': 'Orange', 'year': 2030, 'produced': 128 },
            { 'fruitName': 'Orange', 'year': 2031, 'produced': 137 },
            { 'fruitName': 'Apple', 'year': 2032, 'produced': 147 },
            { 'fruitName': 'Date', 'year': 2033, 'produced': 136 },
            { 'fruitName': 'Date', 'year': 2034, 'produced': 77 },
            { 'fruitName': 'Cherry', 'year': 2035, 'produced': 80 },
            { 'fruitName': 'Cherry', 'year': 2036, 'produced': 143 },
            { 'fruitName': 'Apple', 'year': 2037, 'produced': 89 },
            { 'fruitName': 'Orange', 'year': 2038, 'produced': 75 },
            { 'fruitName': 'Cherry', 'year': 2039, 'produced': 126 },
            { 'fruitName': 'Date', 'year': 2040, 'produced': 106 },
            { 'fruitName': 'Apple', 'year': 2041, 'produced': 74 },
            { 'fruitName': 'Orange', 'year': 2042, 'produced': 73 },
            { 'fruitName': 'Apple', 'year': 2043, 'produced': 106 },
            { 'fruitName': 'Date', 'year': 2044, 'produced': 77 },
            { 'fruitName': 'Banana', 'year': 2045, 'produced': 126 },
            { 'fruitName': 'Banana', 'year': 2046, 'produced': 123 },
            { 'fruitName': 'Orange', 'year': 2047, 'produced': 62 },
            { 'fruitName': 'Orange', 'year': 2048, 'produced': 65 },
            { 'fruitName': 'Apple', 'year': 2049, 'produced': 55 },
            { 'fruitName': 'Apple', 'year': 2050, 'produced': 135 },
            { 'fruitName': 'Orange', 'year': 2051, 'produced': 102 },
            { 'fruitName': 'Date', 'year': 2052, 'produced': 74 },
            { 'fruitName': 'Cherry', 'year': 2053, 'produced': 106 },
            { 'fruitName': 'Cherry', 'year': 2054, 'produced': 133 },
            { 'fruitName': 'Apple', 'year': 2055, 'produced': 142 },
            { 'fruitName': 'Orange', 'year': 2056, 'produced': 131 },
            { 'fruitName': 'Banana', 'year': 2057, 'produced': 53 },
            { 'fruitName': 'Orange', 'year': 2058, 'produced': 143 },
            { 'fruitName': 'Banana', 'year': 2059, 'produced': 77 },
            { 'fruitName': 'Banana', 'year': 2060, 'produced': 53 },
            { 'fruitName': 'Cherry', 'year': 2061, 'produced': 69 },
            { 'fruitName': 'Date', 'year': 2062, 'produced': 119 },
            { 'fruitName': 'Orange', 'year': 2063, 'produced': 144 },
            { 'fruitName': 'Banana', 'year': 2064, 'produced': 139 },
            { 'fruitName': 'Orange', 'year': 2065, 'produced': 96 },
            { 'fruitName': 'Apple', 'year': 2066, 'produced': 148 },
            { 'fruitName': 'Date', 'year': 2067, 'produced': 120 },
            { 'fruitName': 'Banana', 'year': 2068, 'produced': 54 },
            { 'fruitName': 'Orange', 'year': 2069, 'produced': 62 },
            { 'fruitName': 'Cherry', 'year': 2070, 'produced': 93 },
            { 'fruitName': 'Cherry', 'year': 2071, 'produced': 58 },
            { 'fruitName': 'Orange', 'year': 2072, 'produced': 131 },
            { 'fruitName': 'Cherry', 'year': 2073, 'produced': 130 },
            { 'fruitName': 'Banana', 'year': 2074, 'produced': 145 },
            { 'fruitName': 'Apple', 'year': 2075, 'produced': 104 },
            { 'fruitName': 'Orange', 'year': 2076, 'produced': 116 },
            { 'fruitName': 'Apple', 'year': 2077, 'produced': 115 },
            { 'fruitName': 'Date', 'year': 2078, 'produced': 107 },
            { 'fruitName': 'Cherry', 'year': 2079, 'produced': 85 },
            { 'fruitName': 'Orange', 'year': 2080, 'produced': 146 },
            { 'fruitName': 'Date', 'year': 2081, 'produced': 117 },
            { 'fruitName': 'Orange', 'year': 2082, 'produced': 66 },
            { 'fruitName': 'Date', 'year': 2083, 'produced': 131 },
            { 'fruitName': 'Banana', 'year': 2084, 'produced': 80 },
            { 'fruitName': 'Orange', 'year': 2085, 'produced': 126 },
            { 'fruitName': 'Banana', 'year': 2086, 'produced': 76 },
            { 'fruitName': 'Cherry', 'year': 2087, 'produced': 149 },
            { 'fruitName': 'Apple', 'year': 2088, 'produced': 59 },
            { 'fruitName': 'Apple', 'year': 2089, 'produced': 73 },
            { 'fruitName': 'Date', 'year': 2090, 'produced': 78 },
            { 'fruitName': 'Date', 'year': 2091, 'produced': 94 },
            { 'fruitName': 'Cherry', 'year': 2092, 'produced': 133 },
            { 'fruitName': 'Banana', 'year': 2093, 'produced': 104 },
            { 'fruitName': 'Banana', 'year': 2094, 'produced': 89 },
            { 'fruitName': 'Banana', 'year': 2095, 'produced': 116 },
            { 'fruitName': 'Date', 'year': 2096, 'produced': 52 },
            { 'fruitName': 'Apple', 'year': 2097, 'produced': 93 },
            { 'fruitName': 'Apple', 'year': 2098, 'produced': 55 },
            { 'fruitName': 'Date', 'year': 2099, 'produced': 82 },
            { 'fruitName': 'Date', 'year': 2100, 'produced': 122 },
            { 'fruitName': 'Cherry', 'year': 2101, 'produced': 97 },
            { 'fruitName': 'Cherry', 'year': 2102, 'produced': 98 },
            { 'fruitName': 'Date', 'year': 2103, 'produced': 85 },
            { 'fruitName': 'Cherry', 'year': 2104, 'produced': 88 },
            { 'fruitName': 'Banana', 'year': 2105, 'produced': 126 },
            { 'fruitName': 'Banana', 'year': 2106, 'produced': 147 },
            { 'fruitName': 'Orange', 'year': 2107, 'produced': 87 },
            { 'fruitName': 'Apple', 'year': 2108, 'produced': 116 },
            { 'fruitName': 'Date', 'year': 2109, 'produced': 95 },
            { 'fruitName': 'Cherry', 'year': 2110, 'produced': 61 },
            { 'fruitName': 'Date', 'year': 2111, 'produced': 80 },
            { 'fruitName': 'Orange', 'year': 2112, 'produced': 81 },
            { 'fruitName': 'Banana', 'year': 2113, 'produced': 144 },
            { 'fruitName': 'Cherry', 'year': 2114, 'produced': 135 }
        ];
        return fruitProductionData;
    }
}

export interface FruitProduction {
    fruitName: string,
    year: number,
    produced: number
}