export enum CHART {
    BAR = "bar",
    AREA = 'area',
    BUBBLE = 'bubble',
    CANDLESTICK = 'candlestick',
    FULLSTACKEDAREA = 'fullstackedarea',
    FULLSTACKEDBAR = 'fullstackedbar',
    FULLSTACKEDLINE = 'fullstackedline',
    FULLSTACKEDSPLINE = 'fullstackedspline',
    FULLSTACKEDSPLINEAREA = 'fullstackedsplinearea',
    LINE = 'line',
    RANGEAREA = 'rangearea',
    RANGEBAR = 'rangebar',
    SCATTER = 'scatter',
    SPLINE = 'spline',
    SPLINEAREA = 'splinearea',
    STACKEDAREA = 'stackedarea',
    STACKEDBAR = 'stackedbar',
    STACKEDLINE = 'stackedline',
    STACKEDSPLINE = 'stackedspline',
    STACKEDSPLINEAREA = 'stackedsplinearea',
    STEPAREA = 'steparea',
    STEPLINE = 'stepline',
    STOCK = 'stock'
}